version: '3'
services:
    nginx:
        image: nginx:1.15
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build: ./php-fpm
        volumes:
            - ./source:/var/www/html
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=password
      links: 
        - mysql
      ports:
        - 8080:80
      volumes:
          - /sessions
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    https-portal3000:
        image: steveltn/https-portal:1
        ports:
            - '3443:443'
        environment:
            STAGE: local
            DOMAINS: 'localhost -> http://host.docker.internal:3000'